spring:

  rabbitmq:
    host: 47.102.117.127
    port: 5672
    username: admin
    password: admin
    publisher-confirm-type: CORRELATED
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
      retry:
        enabled: true
        max-attempts: 5
    cache:
      channel:
        size: 10
      connection:
        mode: channel
#application:
#  queue: old.ls.repair.record.queue